import { TRADES } from "@/data/trades";
import { SITE_URL } from "@/lib/utils";

export const revalidate = 86400;

// Sitemap index pointing at each shard generated by app/sitemap.ts.
export function GET() {
  const now = new Date().toISOString();
  const shards = ["core", "actualites", ...TRADES.map((t) => t.slug)];

  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...shards.map(
      (id) =>
        `  <sitemap><loc>${SITE_URL}/sitemap/${id}.xml</loc><lastmod>${now}</lastmod></sitemap>`,
    ),
    "</sitemapindex>",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
